##############################################################################
# Cloud Build Configuration for Cloud Run - Studio Italo Santos
# 
# Este arquivo define os passos para build e deploy no Google Cloud Run
# usando Cloud Build para CI/CD automatizado
##############################################################################

steps:
  # ========================================
  # Step 1: Build Docker Image
  # ========================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'
      - '--build-arg'
      - 'NODE_ENV=production'
      - '--cache-from'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'
      - '.'
    timeout: '1200s'

  # ========================================
  # Step 2: Push Image to Container Registry
  # ========================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$SHORT_SHA'
    waitFor: ['build-image']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-latest'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'
    waitFor: ['build-image']

  # ========================================
  # Step 3: Deploy to Cloud Run
  # ========================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-cloud-run'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$SHORT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '${_MEMORY}'
      - '--cpu'
      - '${_CPU}'
      - '--min-instances'
      - '${_MIN_INSTANCES}'
      - '--max-instances'
      - '${_MAX_INSTANCES}'
      - '--timeout'
      - '${_TIMEOUT}'
      - '--set-env-vars'
      - 'NODE_ENV=production,NEXT_TELEMETRY_DISABLED=1'
    waitFor: ['push-image', 'push-latest']

# ========================================
# Images to store in Container Registry
# ========================================
images:
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'

# ========================================
# Configuration Options
# ========================================
timeout: '2400s'  # 40 minutos

options:
  machineType: 'E2_HIGHCPU_8'  # Máquina mais potente para build rápido
  logging: CLOUD_LOGGING_ONLY
  substitutionOption: ALLOW_LOOSE

# ========================================
# Substitutions (Variáveis)
# ========================================
substitutions:
  _SERVICE_NAME: 'italosantos'
  _REGION: 'us-central1'
  _MEMORY: '512Mi'
  _CPU: '1'
  _MIN_INSTANCES: '0'
  _MAX_INSTANCES: '10'
  _TIMEOUT: '300'

# ========================================
# Tags para organização
# ========================================
tags:
  - 'cloud-run'
  - 'nextjs'
  - 'studio-italosantos'
